catalog/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^my-books/$', views.LoanedBooksByUserListView.as_view(), name='my-books'),
    re_path(r'^borred-books/$', views.LoanedBooksStaffListView.as_view(), name='borred-books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librian'),
]
#crud author
urlpatterns += [
    re_path(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
]
#crud book

urlpatterns += [
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^bookinstance/create/(?P<pk>\d+)$', views.BookInstanceCreate.as_view(), name='bookinstance_create'),
    re_path(r'^book/(?P<pk>[-\w]+)/update/$', views.BookInstanceUpdate.as_view(), name='bookinstance_update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', views.BookInstanceDelete.as_view(), name='book_delete'),
]

django_mozilla_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from datetime import date, datetime

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200, help_text='Enter book language')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter breef of summary book')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = [
        ('m', 'Maintance'),
        ('o', 'On loan'),
        ('a', 'Avaible'),
        ('r', 'Reserved'),
    ]
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set book returned'),
                       ('as', 'as'))

    def __str__(self):
        return f'{self.id}-{self.book}'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField('Born', null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

    class Meta:
        ordering = ['last_name']

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='enter date for book',
                                   widget=forms.SelectDateWidget)

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        return data

catalog/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views import generic

from catalog.forms import RenewBookForm
from catalog.models import Book, BookInstance, Author

@login_required
def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Доступные книги (статус = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # Метод 'all()' применён по умолчанию.

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors},
    )


@login_required
@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            messages.success(request, 'Успешно обновили дату возврата книги!')
            return HttpResponseRedirect(reverse('borred-books'))

    else:
        proposed_renewal_data = datetime.date.today() + datetime.timedelta(weeks=4)
        form = RenewBookForm(initial={'renewal_form': proposed_renewal_data})
    context = {'form': form,
               'book_inst': book_inst
               }
    return render(request, 'catalog/book_renew_librarian.html', context=context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin,  generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o')


class LoanedBooksStaffListView(LoginRequiredMixin, generic.ListView):
    # permission_required = 'can_mark_returned'
    model = BookInstance
    paginate_by = 10
    template_name = 'catalog/bookinstacne_list_for_staff.html'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').filter(borrower__isnull=False).order_by('due_back')


class AuthorCreate(generic.edit.CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '12/10/2016'}


class AuthorUpdate(generic.edit.UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth','date_of_death']


class AuthorDelete(SuccessMessageMixin, generic.edit.DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    success_message = 'Вы удалили автора из базы библиотеки!'


class BookCreate(generic.edit.CreateView):
    model = Book
    fields = '__all__'


class BookInstanceCreate(generic.edit.CreateView):
    model = BookInstance
    fields = '__all__'
    initial = {'due_back': '22/01/2022'}
    success_url = reverse_lazy('books')




class BookInstanceUpdate(generic.edit.UpdateView):
    model = BookInstance
    fields = ['book', 'imprint', 'due_back', 'borrower', 'status', ]

    # success_url = reverse_lazy('books')
    success_message = f'Обновили состояние у книги:'


    def get_success_url(self):
        return reverse('book-detail', args=[str(self.object.book.id)])


class BookInstanceDelete(SuccessMessageMixin , generic.edit.DeleteView):
    model = BookInstance
    success_url = reverse_lazy('books')
    success_message = 'Вы удалили книгу!'

catalog/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ author.last_name }} {{ author.first_name }}</h1>
    <p><strong>Birth: </strong>{{ author.date_of_birth }}</p>
    <p><strong>Died: </strong>{{ author.date_of_death }}</p>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Author</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit">
    </form>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Authors:</h1>
    {% if author_list %}
        <ul>
    {% if messages %}
                {% for message in messages %}
                <li class="text-danger">{{ message }}</li>
                {% endfor %}
            {% endif %}
        {% for author in author_list %}

            <li><a href="{{ author.get_absolute_url }}"><strong>{{ author.first_name }} {{ author.last_name }}</strong></a></li>

        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>


  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <p><a href="{% url 'bookinstance_create' book.id %}" >Create Bookinstance</a></p>

    <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    <p><a href="{% url 'bookinstance_update' copy.id %}" >Edit Book</a></p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Book</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit">
    </form>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'base.html' %}
{% block content %}
<h1>Renew onleam</h1>
    <ul>
    <li><strong>Book:  </strong>{{ book_inst.book }}</li>
    <li class="{% if book_inst.is_overdue %}text-danger{% endif %}"><strong>Due back: </strong>{{ book_inst.due_back }}</li>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form}}

        </table>
        <input type="submit" value="submit" />
    </form>
    </ul>

{% endblock %}

catalog/templates/catalog/bookinstacne_list_for_staff.html
{% extends 'base.html'%}
{% block content %}
    {% if user.is_staff %}
        {% if not bookinstance_list %}
            <p>No books on lean</p>
        {% else %}
        <h1>All on lean books: </h1>
            <ul>
            {% if messages %}
                {% for message in messages %}
                <li class="text-danger">{{ message }}</li>
                {% endfor %}
            {% endif %}
            {% for bookinstance in bookinstance_list %}

                <strong>User: </strong>{{ bookinstance.borrower }}
                <li class="{% if bookinstance.is_overdue %} text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title| title }}</a>   {{ bookinstance.due_back }}
                </li>
                {% if perms.catalog.can_mark_returned %}
                    <li>
                        <a href="{% url 'renew-book-librian' bookinstance.id %}">Edit due</a>
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}

    {% endif %}

{% endblock %}

catalog/templates/catalog/bookinstance_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ bookinstance.book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/bookinstance_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create BookInstance</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit">
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base.html' %}

{% block content %}
    {% if perms.catalog.can_mark_returned %}
        <h1>Can modifaed</h1>
    {% endif %}
    <h1>User bookinstanse</h1>
    {% if not bookinstance_list %}
    <p>No book in list for {{ user| title }}</p>
        {% else %}
        {% for bookinstance in bookinstance_list %}
            <ul>
            <li><a href="{% url 'book-detail' bookinstance.book.pk %}">{{ bookinstance.book |title}}</a></li>
            <li><strong>Status: </strong>{{ bookinstance.status }}</li>
            <li><strong>due_back: </strong>
                {% if bookinstance.is_overdue %}
                    <li class="text-danger">
                Book {{ bookinstance.book.title| upper }} is over due. Please return the book!
                {% else %}
                {{ bookinstance.due_back }}</li>
            {% endif %}
            </ul>
        {% endfor %}
    {% endif %}
{% endblock %}